
try:
    int('a')
except ValueError as e:
    print("Oops we can't do that", e)

print('This is it!!!')
